### ISSUE TITLE
коммент 1

### ISSUE THREAD

**Issue by leeiozh** [mickafa/FALT_1#1]
Спасибо за отчет, он сделал моё утро) И спасибо большое за комментарии к коду!
Сейчас будет простыня ворчащего текста, пожалуйста, не пугайся
К этим псевдосоветам можно прислушиваться, можно не прислушиваться, в рейтинг я тебя уже внесла

По коду:
0) ексель - это зло, поэтому лови свой график на питоне (просто на поразбираться)
[for_mickafa.zip](https://github.com/mickafa/FALT_1/files/7494913/for_mickafa.zip)
1) дефайны - это относительное зло, лучше все-таки использовать const
2) в 81 строчку допиши `int message ( const char *text )` , а то он у меня компилить не хотел
3) не уверена, что тебе это актуально, но для ускорения кода есть пара хаков
- если в функции у тебя используется v * v и больше нигде чистая v не используется, лучше ее хранить именно квадратом, тогда ты избавишься от лишнего возведение в степень и извлечения корня, аналогично с r * r 
- величину шага можно варьировать, т.е. если в начале полета при отбработке ступеней нам важна точность, то можно брать и 0.1 с, потом же, когда мы тупо летим по инерции, можно ставить и 10 с - разницы не будет видно
4) для уточнения расчета можно вычислять  `x += vx * DT + 0.5 * ax * DT * DT`
5) к вопросу шага - я бы на начальном этапе таки побольше репортов сделала, а то у тебя НСО больше похожа на шестиугольник, чем на орбиту
6) на ГСО тебя колбасит немного - поварьируй расход и попробуй добиться околопрямой линии
![Screenshot from 2021-11-08 10-26-45](https://user-images.githubusercontent.com/78415756/140700632-7c7d862c-43d6-42ce-95a9-2b394ab60e41.png)

По физике:
Ловко ты с вращением Земли придумал, но это не совсем корректное решение (а мб и корректное, но докажи)
- это чистой воды мухлеж с атмосферой и силой сопротивления. А если бы мы развернулись ниже чем 10h_0, как бы ты искал горизонтальную составлящую: отнимал бы 465 м/с или вычислял линейную на новой высоте?
- представь себе гипотетическую планету, у которой настолько высокая скорость вращения, что угловая скорость * радиус экватора = первая космическая
верно ли, что если я просто подпрыгну на такой планете, я выйду на ее орбиту?

Дальше уже совсем маленькие придирки могли бы быть, но не будут. Ответишь на вопросы - зачту фулл.

На подумать:
По поводу старта с гор - я видела проекты, в которых в высокой горе бурят шахту, откачивают воздух и на чистой пневматике хотят ракеты запускать. Тип так и плотные слои преодолеваем быстро, и топлива немного надо. Какие сложности возникнут при старте с такой установки?

**Comment by mickafa** [comment]
Спасибо за быстрый фидбек, очень приятно. 

1) про const char *text тоже заметил, исправил. У меня был warning, но компилировалось, поэтому заметил не сразу. Рисовать программой пока не научился, будет куда развиваться.

2) Здесь мне всё-таки нужно извлекать корень из v*v, чтобы считать угол в полярных координатах. Хак взял на заметку. Переменный шаг по времени тоже. Эту задачу так оставлю, а если буду решать про солнечный парус, то учту. 

3) Виток по низкой околоземной исключил полностью, почему - приписал дополнение в конце отчёта. И ГСО сделал очень хорошей.

4) С атмосферой - не "мухлёж", а "инженерное решение" :) На самом деле просто не знаю как правильно учитывать. Если бы разворот был ниже 100 км, то придумал бы другой метод, а пока не требуется.

5) На планете с быстрым вращением: если она без атмосферы, то да, прыжок вывел бы на орбиту. Если с атмосферой, то её бы быстро унесло в космос. А пока не унесло, будет большое  скольжение атмосферы относительно поверхности. На Земле этого не наблюдается, поэтому-то примерно пренебрегаю боковым воздействием воздуха.

6) Про старт из тунеля в горе. Это с каким качеством необходимо сделать шахту, чтобы её вакуумировать корпусом ракеты? Пока нет таких технологий. А ещё резкий вход ракеты из шахты в атмосферу = ударному торможению. Проектов стрельбы из пушки по Луне тоже было много, это, видимо, что-то аналогичное. С пневматикой даже хуже, чем с порохом - энергетика ниже. Очень странны такие проекты

**Comment by leeiozh** [comment]
Принято)

В том году у нас была задача про проект Spinlaunch - они хотели запускать ракету с помощью центрифуги, но да, оочень серьезная проблема таких проектов - это ударное торможение и ударная волна, которая тупо разрушит аппарат, какой бы аэродинамичный он ни был, сразу при выходе в атмосферу.

По факту, доп скорость ты "получаешь" при пересаживании в другую СО. То есть на первом этапе ты мог бы вообще ее не учитывать, а при склейке с полетом к Луне просто прибавить себе omega * R_{гсо}. Но твой вариант мб даже честнее. За "мухлеж" прошу прощения, но надо же было для порядка усомниться в таком методе)

Ждем полета к Луне!

**Comment by mickafa** [comment]
Спасибо. В своём методе я тоже сомневаюсь, но в этой задаче и так много допущений, одним больше - одним меньше - не принципиально. Боюсь, что полёт к Луне на солнечном парусе из разряда такой же фантастики, как и пневматический запуск. Посмотрим.

**Comment by leeiozh** [comment]
ты есть в нашем телеграм чате?
а то тут новости прикольные подъехали, Spinlauch запустилась https://vk.com/wall-41126705_100396

**Comment by mickafa** [comment]
Посмотрел. Посмеялся. Но и мы не щи лаптем хлебаем. Наш стартап по второй задаче начался
https://github.com/mickafa/FALT_2
